proxy-providers:
  Airport1:
    url: ""
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ç›´è¿

port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
bind-address: "*"
ipv6: true
unified-delay: true
tcp-concurrent: true
# interface-name: enp6s18
log-level: warning
find-process-mode: 'off'
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
profile:
  store-selected: true
  store-fake-ip: true

external-controller: 0.0.0.0:9090
secret: ""
external-ui: "/etc/nikki/run/ui"
external-ui-name: zashboard
external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"


sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
  skip-domain:
    - "+.baidu.com"

tun:
  enable: true
  # system/gvisor/mixed
  stack: system
  dns-hijack: ["any:53", "tcp://any:53"]
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: true
  respect-rules: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:private_domain,cn_domain"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - "time.*.com"
    - "+.market.xiaomi.com"
    - "+.milkylife.online"
    - "+.xns.one"
  default-nameserver:
    - 223.5.5.5
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
  # nameseverå°½é‡ç”¨è¿è¥å•†æä¾›çš„DNS
  nameserver:
    - https://223.5.5.5/dns-query

proxy-groups:
  - {name: ğŸš€ é»˜è®¤ä»£ç†, type: select, proxies: [â™»ï¸ è‡ªåŠ¨é€‰æ‹©, â™»ï¸ å°æ¹¾è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ç›´è¿]}
  - {name: ğŸ“¹ YouTube, type: select, proxies: [â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ç›´è¿]}
  - {name: ğŸ€ Google, type: select, proxies: [â™»ï¸ å°æ¹¾è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ç›´è¿]}
  - {name: ğŸ¤– AIGC, type: select, proxies: [â™»ï¸ å°æ¹¾è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ç›´è¿]}
  - {name: ğŸ“¹ Pikpak, type: select, proxies: [â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ç›´è¿]}
  - {name: ğŸŸ æ¼ç½‘ä¹‹é±¼, type: select, proxies: [ğŸš€ é»˜è®¤ä»£ç†, â™»ï¸ å°æ¹¾è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ç›´è¿]}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)æ—¥|jp|japan"}
  - {name: ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)å°|tw|taiwan"}
  - {name: ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)ç¾|us|unitedstates|united states"}
  - {name: â™»ï¸ å°æ¹¾è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(å°|TW|(?i)Tai))^((?!(æ¸¯|æ—¥|éŸ©|æ–°|æ·±|ç¾)).)*$"}
  - {name: â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(æ—¥|JP|(?i)Japan))^((?!(æ¸¯|å°|éŸ©|æ–°|ç¾)).)*$" }
  - {name: â™»ï¸ ç¾å›½è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(ç¾|US|(?i)States|America))^((?!(æ¸¯|å°|æ—¥|éŸ©|æ–°)).)*$"}
  - {name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "^((?!(ç›´è¿)).)*$"}
  - {name: ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, type: select, include-all: true}

rules:
  - RULE-SET,AWAvenue-Ads-Rule,REJECT
  - DOMAIN-SUFFIX,hanime1.me,â™»ï¸ ç¾å›½è‡ªåŠ¨
  - DOMAIN-SUFFIX,kchion.me,â™»ï¸ ç¾å›½è‡ªåŠ¨
  - RULE-SET,ehentai_domain,â™»ï¸ ç¾å›½è‡ªåŠ¨
  - RULE-SET,private_domain,ç›´è¿
  - RULE-SET,ai,ğŸ¤– AIGC
  - RULE-SET,youtube_domain,ğŸ“¹ YouTube
  - RULE-SET,pikpak_domain,ğŸ“¹ Pikpak
  - RULE-SET,google_domain,ğŸ€ Google
  - RULE-SET,dlsite_domain,â™»ï¸ æ—¥æœ¬è‡ªåŠ¨
  - RULE-SET,apple_domain,ç›´è¿
  - RULE-SET,steam_domain,ç›´è¿
  - RULE-SET,geolocation-!cn,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,cn_domain,ç›´è¿

  - RULE-SET,private_ip,ç›´è¿,no-resolve
  - RULE-SET,apple_ip,ç›´è¿,no-resolve
  - RULE-SET,google_ip,ğŸ€ Google,no-resolve
  - RULE-SET,cn_ip,ç›´è¿
  
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼

rule-providers:
    AWAvenue-Ads-Rule:
        behavior: domain        
        format: yaml
        interval: 86400        
        type: http
        url: https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main//Filters/AWAvenue-Ads-Rule-Clash.yaml
    ai:
        behavior: domain
        format: mrs
        interval: 86400
        type: http
        url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs
    apple_domain:
        behavior: domain
        format: mrs
        interval: 86400
        type: http
        url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.mrs
    apple_ip:
        behavior: ipcidr
        format: mrs
        interval: 86400
        type: http
        url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/apple.mrs
    cn_domain:
        behavior: domain
        format: mrs
        interval: 86400
        type: http
        url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs
    cn_ip:
        behavior: ipcidr
        format: mrs
        interval: 86400
        type: http
        url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs
    dlsite_domain:
        behavior: domain
        format: mrs
        interval: 86400
        type: http
        url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/dlsite.mrs
    ehentai_domain:
        behavior: domain
        format: mrs
        interval: 86400
        type: http
        url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/ehentai.mrs
    geolocation-!cn:
        behavior: domain
        format: mrs
        interval: 86400
        type: http
        url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs
    google_domain:
        behavior: domain
        format: mrs
        interval: 86400
        type: http
        url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs
    google_ip:
        behavior: ipcidr
        format: mrs
        interval: 86400
        type: http
        url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs
    private_domain:
        behavior: domain
        format: mrs
        interval: 86400
        type: http
        url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs
    private_ip:
        behavior: ipcidr
        format: mrs
        interval: 86400
        type: http
        url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs
    speedtest_domain:
        behavior: domain
        format: mrs
        interval: 86400
        type: http
        url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs
    steam_domain:
        behavior: domain
        format: mrs
        interval: 86400
        type: http
        url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam@cn.mrs
    youtube_domain:
        behavior: domain
        format: mrs
        interval: 86400
        type: http
        url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs
    pikpak_domain:
        behavior: domain
        format: mrs
        interval: 86400
        type: http
        url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/pikpak.mrs